<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFpG50zr\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFpG50zr/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerFpG50zr.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerFpG50zr\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerFpG50zr\App_KernelProdContainer([
    'container.build_hash' => 'FpG50zr',
    'container.build_id' => '36f601bc',
    'container.build_time' => 1740023765,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFpG50zr');
